/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit/break-glass/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a break-glass cross-tenant audit query
         * @description Reads `audit_events` rows for a tenant other than the requesting principal's
         *     home tenant. Requires an operator JWT (audience `collectmind-operator`).
         *     Writes a `kind=break_glass` audit row in the same database transaction as
         *     the bypassed SELECT; if the audit-row write fails the transaction aborts
         *     and the response is 500 (the audit row's absence is itself a signal).
         *
         */
        post: operations["breakGlassAuditQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BreakGlassRequest: {
            /** @description The target tenant identifier whose audit events are to be read. The
             *     bypass primitive refuses to read rows outside this scope; widening the
             *     scope mid-flight is impossible by construction (the service-principal
             *     SELECT is parameterized on this value).
             *      */
            tenant_scope: string;
            /** @description The audit-event correlation identifier. Matches the same correlation_id
             *     shape used by the regular audit-query API.
             *      */
            correlation_id: string;
            /**
             * @description The documented enumeration of break-glass reasons. Captured in the
             *     `kind=break_glass` audit row. Extending the enumeration requires an
             *     ADR amendment to ADR-0007.
             *
             * @enum {string}
             */
            reason_code: "incident_response" | "legal_hold" | "regulator_request" | "support_escalation" | "operator_self_audit";
        };
        AuditEventList: {
            events: components["schemas"]["AuditEvent"][];
            total: number;
        };
        /** @description Same shape as the AuditEvent type in `query-api.v1.yaml`, with the `kind`
         *     enumeration extended to include the four new kinds shipped by feature 002.
         *      */
        AuditEvent: {
            event_id: string;
            tenant_id: string;
            /** @enum {string} */
            kind: "generated" | "validated" | "deployed" | "outcome" | "break_glass" | "tenant_config_change" | "deployment_rejected" | "vehicle_assignment_change";
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
            /** @description Per-kind minimum field set. Required keys per kind:
             *     - generated, validated, deployed, outcome: see feature 001's audit primitive (FR-017a).
             *     - break_glass:                operator_principal_subject, tenant_scope, reason_code, correlation_id
             *     - tenant_config_change:       service_principal_subject, target_tenant_id, prior_values, new_values, correlation_id
             *     - deployment_rejected:        policy_ref, target_vehicle_id, policy_declared_tenant_id, vehicle_owning_tenant_id, correlation_id
             *     - vehicle_assignment_change:  service_principal_subject, vehicle_id, prior_tenant_id, new_tenant_id, reason_code, correlation_id
             *      */
            extras?: Record<string, never>;
        };
        Error: {
            /** @description A machine-readable error code from the documented enumeration. */
            code: string;
            /** @description A human-readable error message. MUST NOT leak cross-tenant identifiers. */
            message: string;
            /** @description The request's correlation identifier for log lookup. */
            correlation_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    breakGlassAuditQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreakGlassRequest"];
            };
        };
        responses: {
            /** @description Audit events for the named tenant scope. The response is identical in
             *     shape to the regular audit-query response so the operator-facing surface
             *     in a future feature can render it with the same code.
             *      */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventList"];
                };
            };
            /** @description Malformed request (invalid reason_code, missing tenant_scope, etc.) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description JWT audience claim is not `collectmind-operator`. Returned without revealing
             *     whether the named tenant scope exists.
             *      */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No audit events match the named tenant_scope + correlation_id. Returned
             *     without revealing whether the tenant exists or whether other correlation
             *     ids exist for that tenant.
             *      */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Audit-row write failed; the bypassed SELECT was rolled back. The operator
             *     sees no audit events; the operator-side incident-response procedure is to
             *     check the orchestration-api logs and the Prometheus
             *     `collectmind_break_glass_audit_write_failure_total` counter.
             *      */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
