/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a diagnostic finding for the policy loop
         * @description Accepts a diagnostic finding and enqueues it for the four-node graph.
         *     Idempotent on the composite key (tenant_id, finding_id) per FR-012.
         *
         */
        post: operations["publishDiagnosticFinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/erasure-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a GDPR/CCPA right-to-erasure request */
        post: operations["submitErasureRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (verifies SLM weights, DB, Redis, Kafka) */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiagnosticFindingEvent: {
            /** @description Semver. The supported major is 1; unknown additive minor/patch fields are tolerated and ignored. */
            schema_version: string;
            finding_id: string;
            /**
             * @description In feature 001 only brake_wear_early_stage is accepted.
             * @enum {string}
             */
            anomaly_type: "brake_wear_early_stage";
            hypothesis_class: string;
            hypothesis_statement: string;
            candidate_signals: string[];
            vehicle_scope: string[];
            upstream_confidence: number;
        };
        AcceptedReceipt: {
            tenant_id: string;
            finding_id: string;
            correlation_id: string;
            /** Format: date-time */
            accepted_at: string;
            /** @default false */
            idempotent_replay: boolean;
        };
        ErasureRequest: {
            /** @enum {string} */
            subject_kind: "vehicle" | "finding" | "principal";
            subject_identifier: string;
            /**
             * @default erased
             * @enum {string}
             */
            mode: "erased" | "redacted";
        };
        ErasureReceipt: {
            request_id: string;
            /** Format: date-time */
            target_completion_at: string;
        };
        Error: {
            /** @description Stable error code (e.g., AUTH_INVALID_TOKEN, AUTH_EXPIRED, AUTH_TENANT_MISSING, SCHEMA_VALIDATION_FAILED, SCHEMA_VERSION_UNSUPPORTED, VSS_INVALID_SIGNAL, RATE_LIMITED, NOT_FOUND). */
            code: string;
            /** @description HTTP-equivalent status code. */
            status: number;
            /** @description Human-readable reason. */
            reason: string;
            /** @description Optional details object. Authentication failures MUST NOT echo the inbound payload or any token claim other than the rejection code. */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    publishDiagnosticFinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticFindingEvent"];
            };
        };
        responses: {
            /** @description Accepted, enqueued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedReceipt"];
                };
            };
            /** @description Schema validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication failure (missing or invalid token, expired token, missing or empty tenant_id claim) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Idempotent replay (already accepted) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedReceipt"];
                };
            };
            /** @description Schema_version major unsupported */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitErasureRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErasureRequest"];
            };
        };
        responses: {
            /** @description Accepted; dispatcher will propagate to all stores */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureReceipt"];
                };
            };
            /** @description Authentication failure */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready (returns the failing dependency in body) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
