/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active version of a policy */
        get: operations["getPolicyById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the version history of a policy (newest first) */
        get: operations["listPolicyVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle-groups/{group_id}/active-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active policy version targeting a given vehicle group */
        get: operations["getActivePolicyForGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{finding_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the outcome record linked to a diagnostic finding */
        get: operations["getOutcomeForFinding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/{correlation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the audit-event chain for a correlation identifier */
        get: operations["getAuditTrail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CollectionPolicySpec: {
            policy_id: string;
            version: string;
            signals: {
                vss_name: string;
                sample_rate_hz: number;
                priority: number;
            }[];
            trigger_conditions: {
                /** @enum {string} */
                kind: "threshold" | "time_window" | "geofence" | "scheduled";
                params: {
                    [key: string]: unknown;
                };
            }[];
            collection_window_hours: number;
            hypothesis: string;
            vehicle_scope: string[];
            data_governance_flags: {
                pii_consent: boolean;
                has_pii_signal: boolean;
            };
            confidence_threshold: number;
            generated_from_session_id: string;
            originating_finding: {
                tenant_id: string;
                finding_id: string;
            };
            prompt_template_version?: string;
            slm_repo?: string;
            slm_revision_sha?: string;
            /** @enum {string} */
            slm_runtime?: "vllm" | "llama_cpp" | "stub";
            slm_runtime_version?: string;
            /** @enum {string} */
            slm_quantization?: "bf16" | "gguf-q4_k_m" | "none";
            slm_decoding_seed?: number;
            /** Format: date-time */
            created_at?: string;
        };
        PolicyOutcome: {
            outcome_id: string;
            originating_finding: {
                tenant_id: string;
                finding_id: string;
            };
            policy_ref?: {
                tenant_id?: string;
                policy_id?: string;
                version?: string;
            };
            /** @enum {string} */
            hypothesis_state: "confirmed" | "ruled_out" | "no_data";
            /** Format: date-time */
            evaluated_at: string;
            signals_collected_count?: number;
            data_quality_score?: number;
            evidence_summary?: {
                [key: string]: unknown;
            };
        };
        AuditEvent: {
            event_id: string;
            /** @enum {string} */
            kind: "accepted" | "rejected" | "generated" | "validated" | "deployed" | "outcome" | "erasure";
            /** Format: date-time */
            occurred_at: string;
            correlation_id: string;
            principal_subject: string;
            slm_repo?: string;
            slm_revision_sha?: string;
            slm_runtime?: string;
            slm_runtime_version?: string;
            slm_quantization?: string;
            slm_decoding_seed?: number;
            prompt_template_version?: string;
            inbound_schema_version?: string;
            time_acceleration_factor?: number;
            policy_ref?: Record<string, never>;
            deployment_ref?: Record<string, never>;
            outcome_ref?: Record<string, never>;
        };
        Error: {
            code: string;
            status: number;
            reason: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPolicyById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPolicySpec"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPolicyVersions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPolicySpec"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getActivePolicyForGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPolicySpec"];
                };
            };
            /** @description No active policy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOutcomeForFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outcome record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOutcome"];
                };
            };
            /** @description Not found (finding unknown or outcome not yet evaluated) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAuditTrail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                correlation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events in occurrence order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            /** @description Unknown correlation id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
