import { Link } from "react-router-dom";
import { MermaidDiagram } from "@/components/MermaidDiagram";
import { SloTile } from "@/components/SloTile";

const ARCHITECTURE_CHART = `flowchart LR
  subgraph EDGE["External"]
    AI["AI Technician<br/>diagnostic findings"]
    COLL["Collector AI<br/>vehicle control plane"]
  end
  subgraph API["CollectMind cloud control plane"]
    ORCH["Orchestration API<br/>POST /findings"]
    RL["Per-tenant rate limiter<br/>token bucket · Redis · 3-branch"]
    GRAPH["LangGraph<br/>4 nodes (Orch, Gen, Validate, Deploy)"]
    SLM["SLM container<br/>Qwen2.5-7B-Instruct · vLLM · outlines"]
    REG["Registry<br/>Postgres + TimescaleDB · RESTRICTIVE RLS"]
    AUDIT["audit_events<br/>FR-017a immutable chain"]
    QRY["Query API<br/>policies · audit · outcome"]
    ADM["Audit-Admin<br/>break-glass · operator-issuer"]
    OBS["Observability<br/>OTel · Prometheus · Grafana · Alertmanager"]
  end
  AI -->|tenant JWT| ORCH
  ORCH --> RL --> GRAPH
  GRAPH --> SLM
  GRAPH --> REG
  GRAPH --> COLL
  REG --> AUDIT
  ORCH -.->|reads| QRY
  ADM -. service principal .-> AUDIT
  QRY --- REG
  GRAPH --> OBS
  AUDIT --> OBS`;

const PRINCIPLES = [
  {
    label: "Production-grade by default",
    body: "Every feature held to the same bar as feature 001 closure. No demo framing.",
  },
  {
    label: "SLM-first, isolated, swappable",
    body: "Real SLM under deterministic decoding in contract + integration. Frontier LLM is opt-in.",
  },
  {
    label: "Deterministic CI budget",
    body: "Real SLM at temp=0 + fixed seed for correctness. Deterministic stub for load + soak. workflow_dispatch for full runs.",
  },
  {
    label: "No mocked subsystems",
    body: "Postgres + TimescaleDB, Redis, Kafka are real. Mocks only at clearly external boundaries.",
  },
  {
    label: "Audit is a feature, not a log",
    body: "Every policy-generation, validation, deployment, outcome, and erasure writes an immutable row.",
  },
];

export function Landing() {
  return (
    <div className="px-4 lg:px-8 py-8 space-y-10 max-w-6xl">
      <section className="space-y-3">
        <div className="pill-accent">Constitution v1.0.1 · two features shipped</div>
        <h1 className="text-3xl lg:text-4xl font-semibold tracking-tight text-zinc-50">
          The diagnostic-to-collection loop, closed under SLM rigor.
        </h1>
        <p className="text-zinc-300 max-w-3xl">
          CollectMind sits between a diagnostic reasoning system and a vehicle data-collection
          control plane. It turns a diagnostic finding into a versioned, signed, audit-trailed
          telemetry policy — generated by an open-weight SLM under decode-time grammar constraints
          and deployed under per-tenant isolation. Two features shipped (
          <a className="text-accent-300 underline" href="/docs/feature-001-readiness-review">
            policy loop
          </a>{" "}
          and{" "}
          <a className="text-accent-300 underline" href="/docs/feature-002-readiness-review">
            multi-tenant isolation
          </a>
          ); every NON-NEGOTIABLE constitutional principle PASS with a named artifact.
        </p>
        <div className="flex flex-wrap gap-2 pt-2">
          <Link to="/operator" className="btn-primary">
            Run the loop →
          </Link>
          <Link to="/tenants" className="btn-secondary">
            Tenant isolation
          </Link>
          <Link to="/slo" className="btn-secondary">
            Measured SLOs
          </Link>
          <Link to="/docs" className="btn-secondary">
            Constitution + ADRs
          </Link>
        </div>
      </section>

      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        <SloTile
          label="Dashboard lag (SC-006)"
          value="2.11"
          unit="s"
          budget="10 s"
          headroom="~5×"
          source="T136 · 5-run max · feature 001"
        />
        <SloTile
          label="Quickstart e2e (SC-008)"
          value="3"
          unit="s"
          budget="600 s"
          headroom="~200×"
          source="T292 · warm Compose · feature 002"
        />
        <SloTile
          label="Line coverage (Principle IV)"
          value="85.36"
          unit="%"
          budget="≥ 85 %"
          headroom="+0.36 pp"
          source="T285 · across-tier · local"
        />
        <SloTile
          label="Test bar"
          value="329 / 17 / 24"
          unit="unit / contract / int"
          source="Phase 14 closure · feature 002"
        />
      </section>

      <section>
        <h2 className="text-lg font-semibold text-zinc-100 mb-3">Architecture</h2>
        <MermaidDiagram chart={ARCHITECTURE_CHART} caption="Cloud control plane. The SLM container has no outbound network except OTLP (Principle XIII)." />
      </section>

      <section>
        <h2 className="text-lg font-semibold text-zinc-100 mb-3">Principles surfaced by this demo</h2>
        <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {PRINCIPLES.map((p) => (
            <li key={p.label} className="panel p-4">
              <div className="font-medium text-zinc-100">{p.label}</div>
              <div className="text-sm text-zinc-400 mt-1">{p.body}</div>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
