"""Named Prometheus metrics emitted by CollectMind (FR-014, Constitution Principle V).

The Prometheus exposition uses the OTel metrics SDK in production via ADOT in cloud and
the OTLP exporter locally. For the foundation smoke test we expose Prometheus directly
through `prometheus_client` so `/metrics` is scrape-ready without a collector.
"""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, generate_latest


REGISTRY_NAMESPACE = "collectmind"


# Pipeline funnel counters (FR-014).
diagnostic_findings_received_total = Counter(
    f"{REGISTRY_NAMESPACE}_diagnostic_findings_received_total",
    "Diagnostic findings accepted by the inbound interface.",
    labelnames=("tenant_id",),
)
policy_generated_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_generated_total",
    "Policies generated by the Policy Generator node.",
    labelnames=("tenant_id",),
)
policy_validated_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_validated_total",
    "Policies that passed the validator.",
    labelnames=("tenant_id",),
)
policy_deployed_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_deployed_total",
    "Policies accepted by the downstream control plane.",
    labelnames=("tenant_id",),
)
policy_outcome_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_outcome_total",
    "Outcome records written by the feedback worker.",
    labelnames=("tenant_id", "state"),
)
policy_retry_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_retry_total",
    "Validator-failure retries routed back to the Policy Generator (Principle XII).",
    labelnames=("tenant_id",),
)
dead_letter_queue_depth = Gauge(
    f"{REGISTRY_NAMESPACE}_dead_letter_queue_depth",
    "Current depth of the dead-letter queue.",
    labelnames=("kind",),
)
authentication_failure_total = Counter(
    f"{REGISTRY_NAMESPACE}_authentication_failure_total",
    "Inbound JWT verification failures.",
    labelnames=("reason",),
)
time_to_deploy_seconds = Histogram(
    f"{REGISTRY_NAMESPACE}_time_to_deploy_seconds",
    "End-to-end latency from diagnostic event accepted to policy deployed.",
    buckets=(0.5, 1.0, 2.0, 4.0, 8.0, 12.0, 20.0, 30.0, 60.0, 120.0),
    labelnames=("tenant_id",),
)


# SC-004 query latency, SC-010 outcome write delay, SC-012 availability counters.
query_request_latency_seconds = Histogram(
    f"{REGISTRY_NAMESPACE}_query_request_latency_seconds",
    "Latency of the query API per route (SC-004).",
    buckets=(0.01, 0.025, 0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0),
    labelnames=("route", "status_class"),
)
policy_outcome_write_delay_seconds = Histogram(
    f"{REGISTRY_NAMESPACE}_policy_outcome_write_delay_seconds",
    "Wall-clock delta from policy collection-window close to outcome row written (SC-010).",
    buckets=(1.0, 5.0, 15.0, 30.0, 60.0, 120.0, 300.0, 600.0, 1800.0),
    labelnames=("tenant_id",),
)
http_request_total = Counter(
    f"{REGISTRY_NAMESPACE}_http_request_total",
    "All HTTP requests served by the orchestration and query APIs (SC-012).",
    labelnames=("route", "status_class"),
)


# SLM-specific metrics (Principle XIII, ADR-0002).
slm_generation_latency_seconds = Histogram(
    f"{REGISTRY_NAMESPACE}_slm_generation_latency_seconds",
    "Per-call SLM generation latency.",
    buckets=(0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0),
    labelnames=("runtime",),
)
slm_constraint_violation_total = Counter(
    f"{REGISTRY_NAMESPACE}_slm_constraint_violation_total",
    "Constraint-violation count from the constrained decoder (ADR-0003).",
    labelnames=("runtime",),
)
slm_weight_sha_active = Gauge(
    f"{REGISTRY_NAMESPACE}_slm_weight_sha_active",
    "Indicator metric labeled with the active SLM weight SHA.",
    labelnames=("sha",),
)
slm_runtime_image_digest_active = Gauge(
    f"{REGISTRY_NAMESPACE}_slm_runtime_image_digest_active",
    "Indicator metric labeled with the active SLM runtime image digest.",
    labelnames=("digest", "runtime"),
)


def render_prometheus() -> bytes:
    """Return the Prometheus exposition for the registered metrics."""
    return generate_latest()
