"""Named Prometheus metrics emitted by CollectMind (FR-014, Constitution Principle V).

The Prometheus exposition uses the OTel metrics SDK in production via ADOT in cloud and
the OTLP exporter locally. For the foundation smoke test we expose Prometheus directly
through `prometheus_client` so `/metrics` is scrape-ready without a collector.
"""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, generate_latest


REGISTRY_NAMESPACE = "collectmind"


# Pipeline funnel counters (FR-014).
diagnostic_findings_received_total = Counter(
    f"{REGISTRY_NAMESPACE}_diagnostic_findings_received_total",
    "Diagnostic findings accepted by the inbound interface.",
    labelnames=("tenant_id",),
)
policy_generated_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_generated_total",
    "Policies generated by the Policy Generator node.",
    labelnames=("tenant_id",),
)
policy_validated_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_validated_total",
    "Policies that passed the validator.",
    labelnames=("tenant_id",),
)
policy_deployed_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_deployed_total",
    "Policies accepted by the downstream control plane.",
    labelnames=("tenant_id",),
)
policy_outcome_total = Counter(
    f"{REGISTRY_NAMESPACE}_policy_outcome_total",
    "Outcome records written by the feedback worker.",
    labelnames=("tenant_id", "state"),
)
dead_letter_queue_depth = Gauge(
    f"{REGISTRY_NAMESPACE}_dead_letter_queue_depth",
    "Current depth of the dead-letter queue.",
    labelnames=("kind",),
)
authentication_failure_total = Counter(
    f"{REGISTRY_NAMESPACE}_authentication_failure_total",
    "Inbound JWT verification failures.",
    labelnames=("reason",),
)
time_to_deploy_seconds = Histogram(
    f"{REGISTRY_NAMESPACE}_time_to_deploy_seconds",
    "End-to-end latency from diagnostic event accepted to policy deployed.",
    buckets=(0.5, 1.0, 2.0, 4.0, 8.0, 12.0, 20.0, 30.0, 60.0, 120.0),
    labelnames=("tenant_id",),
)


# SLM-specific metrics (Principle XIII, ADR-0002).
slm_generation_latency_seconds = Histogram(
    f"{REGISTRY_NAMESPACE}_slm_generation_latency_seconds",
    "Per-call SLM generation latency.",
    buckets=(0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0),
    labelnames=("runtime",),
)
slm_constraint_violation_total = Counter(
    f"{REGISTRY_NAMESPACE}_slm_constraint_violation_total",
    "Constraint-violation count from the constrained decoder (ADR-0003).",
    labelnames=("runtime",),
)
slm_weight_sha_active = Gauge(
    f"{REGISTRY_NAMESPACE}_slm_weight_sha_active",
    "Indicator metric labeled with the active SLM weight SHA.",
    labelnames=("sha",),
)
slm_runtime_image_digest_active = Gauge(
    f"{REGISTRY_NAMESPACE}_slm_runtime_image_digest_active",
    "Indicator metric labeled with the active SLM runtime image digest.",
    labelnames=("digest", "runtime"),
)


def render_prometheus() -> bytes:
    """Return the Prometheus exposition for the registered metrics."""
    return generate_latest()
